### ISSUE TITLE
Xcode crashes when saving after adding C functions or blocks.

### ISSUE THREAD

**Issue by dehesa** [zolomatok/ZMDocItemInspector#2]
Hi @zolomatok,

First of all, thanks for the useful plugin. It is a great timesaver and orientation helper. I love it!

I have only been using ZMDocItemInspector for a couple of days and I notice that Xcode crashes the moment I press ⌘+S (saving) just after declaring a new C function or when calling a block (within a block).

I couldn't really test it through to give you a better crash report, since I am using it for my current work. If I have more time later I will do so. What I can say with security is that it is the influence of your Plugin, since doing the exact same thing without your plugin installed, Xcode doesn't crash (I have other third party plugins installed).

**Comment by zolomatok** [comment]
Thank you for bringing this to my attention!
I will fix the issue in the evening.

**Comment by zolomatok** [comment]
@dehesa I've tried both those things but the plugin does not crash for me. If it's not super secret, can you share your declarations with me? Thank you

**Comment by dehesa** [comment]
Hi @zolomatok,
I detected the problem with a project that is sadly not open source (yet); however, I will try to do the same with some other big projects we have at our company which are open source. Give me a couple of days to try it out, please ;)

**Comment by zolomatok** [comment]
That would be great, thank you!
