### ISSUE TITLE
Not working on Xcode 6.3.2

### ISSUE THREAD

**Issue by mojtabacazi** [zolomatok/ZMDocItemInspector#3]
Adding plugin with Alcatraz won't do anything on Xcode 6.3.2

**Comment by zolomatok** [comment]
Thank you for bringing it to my attention!
I fixed the issue, you can update the plugin.

Please get back to me whether the problem is fixed or not for you!

**Comment by ghost** [comment]
It swipes really weird when swiping up and down on the pane (showing the document pane underneath it) and lags Xcode terribly. (6.3.2)

**Comment by zolomatok** [comment]
Thanks for the heads up @antgly ! 
Can you tell me how many symbols (elements) you have in the inspector? It runs smoothly for me with around 60 symbols in a single file.
