### ISSUE TITLE
Could not work on Xcode 6.4

### ISSUE THREAD

**Issue by zhoumopashan** [zolomatok/ZMDocItemInspector#4]
Could not work on Xcode 6.4 while add it by Alcatraz.

**Comment by zolomatok** [comment]
Fixed by @Hs-Yeah , please try again

**Comment by zhoumopashan** [comment]
@zolomatok @Hs-Yeah Thinks , I tried it and it works ！Your plugin help me very much , good job!

**Comment by zolomatok** [comment]
Great, happy to help!
