### ISSUE TITLE
Does not work on Xcode 7

### ISSUE THREAD

**Issue by pronebird** [zolomatok/ZMDocItemInspector#6]

**Comment by hsleedevelop** [comment]
In my case, 
XCode7 crashes sometimes 'cause using this plugin

Please fix prob.

**Comment by oit63** [comment]
if you are using Xcode 7.0

add
0420B86A-AA43-4792-9ED0-6FE0F2B16A13

to your downloaded ZMDocItemInspector Project's  Info.plist  at
DVTPlugInCompatibilityUUIDs  array at one new item 
 then run the project, restart Xcode,
the bundle would be found.

**Comment by iKazakov** [comment]
how to fix for alcatraz?

**Comment by zolomatok** [comment]
@iKazakov , @ForrestAlfred  , @pronebird  Apologies for the delay, I've updated the plugin so that it works with Xcode 7.0 now.

@evercry I will work out a fix soon!

**Comment by iKazakov** [comment]
nice news :) tnx
