### ISSUE TITLE
Not working in xcode 7.x + 

### ISSUE THREAD

**Issue by Pyrolr** [zolomatok/ZMDocItemInspector#7]
I have tried adding plugin via Alcatraz in xcode 7,7.1,7.2 but in none of the xcode menu is visible 
Any one is able to have plugin working in xcode 7.x + ? 
Is there any setting needs to be enable ? I have restarted xcode multiple times
Also it does not ask me to load a bundle alert which is asked for other plugins

**Comment by Pyrolr** [comment]
Solved by adding DVTPlugInCompatibilityUUIDs xcode

**Comment by zolomatok** [comment]
Sorry @Pyrolr I was under the impression that I have already added Xcode 7.2 compatiblity. I've checked and the 7.2 UUID was really missing.
It seems Xcode 7.2 beta and 7.2 proper had different UUIDs (?)

Just pushed a commit with the proper UUID.
I hope you enjoy using the plugin.
